language: rust

rust:
  - stable
#  - beta
#  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry"

script:
  - cd litcontainers
  - cargo build --all
  - cargo test --all
  - cd ..
  - cd litio
  - cargo build --all
  - cargo test --all